MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(12, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(12, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 6);9
DAMG;LLMAgent|DeepSeek|deepseek-chat|Green|4;7
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(12, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|4;(12, 9);9
DEAD;Target
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 8)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|4;(16, 9);9
DEAD;Target (5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 10)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 10)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(15, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(14, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 10)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(14, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(15, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(13, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(12, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(11, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 10)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 9)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(15, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(14, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(11, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(10, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 7)
ATTK;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(9, 8);9
DAMG;LLMAgent|DeepSeek|deepseek-chat|Green|4;7
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(13, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(12, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 7);9
DAMG;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;7
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 7);9
DAMG;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;7
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(8, 7)
ATTK;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5;(7, 6);9
DAMG;LLMAgent|DeepSeek|deepseek-chat|Green|1;7
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 7);9
DEAD;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|5
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(12, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(11, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(9, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(6, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(5, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(5, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(6, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 6)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|4;(10, 7);9
DAMG;LLMAgent|DeepSeek|deepseek-chat|Green|6;7
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(6, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(5, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 13)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 9)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 9);9
DEAD;Target (3)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 10)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(5, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(6, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 9)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 9)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 10)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 9)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 10)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 10)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 9)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 9)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 10)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 9)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 9)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 7);9
DAMG;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;7
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 7);9
DAMG;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;7
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 8)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|4;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5);9
DEAD;LLMAgent|DeepSeek|deepseek-chat|Green|4
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 8)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2;(8, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 7);9
DEAD;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|2
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(6, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(6, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 3)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(12, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(12, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(6, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(6, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(6, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(6, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(5, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(4, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(3, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(3, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(4, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(5, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(5, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(6, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(6, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(6, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(6, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(5, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(5, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(6, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 5)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 2)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 3)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(12, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(12, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(11, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(11, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(10, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 7)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6);[Moved by wave effect!]
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(10, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6);9
DAMG;LLMAgent|DeepSeek|deepseek-chat|Green|6;7
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(7, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(8, 6)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|6;(9, 6)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
ATTK;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 6);9
DEAD;LLMAgent|DeepSeek|deepseek-chat|Green|6
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 11)
MOVE;LLMAgent|Gemini|gemini-2.5-flash-lite|Red|3;(10, 12);[Moved by wave effect!]
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(7, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(8, 4)
MOVE;LLMAgent|DeepSeek|deepseek-chat|Green|1;(9, 4)
